[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
rarible_editions = "DsaxZA54w7N9z8jxobtzy3rhQQmXjngjvJNvX1HubtkJ"
rarible_editions_controls = "bozxrH9R1qvQh7P1gid3X8DRXK1UmVckit6XxGAUN72"
rarible_marketplace = "61AUdCJkaaw2b3Byhp9gLyK6rvt8DTsUoGTKwnvEZMaf"

[programs.localnet]
rarible_editions = "DsaxZA54w7N9z8jxobtzy3rhQQmXjngjvJNvX1HubtkJ"
rarible_editions_controls = "bozxrH9R1qvQh7P1gid3X8DRXK1UmVckit6XxGAUN72"
rarible_marketplace = "61AUdCJkaaw2b3Byhp9gLyK6rvt8DTsUoGTKwnvEZMaf"

[programs.mainnet]
rarible_editions = "DsaxZA54w7N9z8jxobtzy3rhQQmXjngjvJNvX1HubtkJ"
rarible_editions_controls = "bozxrH9R1qvQh7P1gid3X8DRXK1UmVckit6XxGAUN72"
rarible_marketplace = "61AUdCJkaaw2b3Byhp9gLyK6rvt8DTsUoGTKwnvEZMaf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "RUST_LOG= yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 50000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899


[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[[test.validator.clone]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"

[[test.validator.clone]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "5hx15GaPPqsYA61v6QpcGPpo125v7rfvEfZQ4dJErG5V"
