[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
wen_new_standard = "62ZfKMe7eGSJNTcprjr8UHQgsRYoX8UpvvbD1XLv5mMz"
wen_royalty_distribution = "WixB9EBhWi6ZWjAW5uNJ52ku6SEHPgT25exguqxRtSm"
wen_transfer_guard = "7en3fCXrr49VpKazWYTJ31uGDVQTRmECiQC9RJ6hzudA"
wen_wns_marketplace = "8xBBKGGihbs318FzGLR2pS7YdMnuL3uuF7T92YtF3wu7"

[programs.localnet]
wen_new_standard = "wns1gDLt8fgLcGhWi5MqAqgXpwEP1JftKE9eZnXS1HM"
wen_royalty_distribution = "diste3nXmK7ddDTs1zb6uday6j4etCa9RChD8fJ1xay"
wen_transfer_guard = "LockdqYQ9X2kwtWB99ioSbxubAmEi8o9jqYwbXgrrRw"
wen_wns_marketplace = "sALEeD9VGNquoGSXvUAKLeVbXdjiPCb3FTuTm1xSLod"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "RUST_LOG= yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 50000
shutdown_wait = 2000
upgradeable = false
